### ISSUE TITLE
Unable to auth

### ISSUE THREAD

**Issue by marishlucas** [checkmarble/marble#17]
Accessing the frontend using the provided link by [remix-serve] - (http://172.18.0.6:8080) (localhost:8080 doesn't work), and logging through the google ouath, the following errors are shown in the browser console:

![image](https://github.com/checkmarble/marble/assets/54138203/ad627622-1f41-43ff-b763-71573a66c396)

console logs:

```
marble-app       | GET /sign-in 200 - - 45.834 ms
marble-api       | 2024-04-19T06:33:41Z INFO GET /liveness status=200 latency=0 client_ip=127.0.0.1 method=GET path=/liveness data_length=24 user_agent=Wget error=""
marble-app       | POST /sign-in?_data=routes%2F_auth%2B%2Fsign-in 204 - - 159.213 ms
marble-app       | GET /sign-in?_data=routes%2F_auth%2B%2Fsign-in 200 - - 7.260 ms
marble-app       | GET /sign-in?_data=root 200 - - 5.009 ms
```

browser : Mozilla Firefox 124.0.1
system : Arch Linux, Manjaro

**Comment by Pascal-Delange** [comment]
Hi @marishlucas , Sorry for the late answer, I did not notice the ping on the issue.
We'll have a look at it

**Comment by Pascal-Delange** [comment]
P.S. after a quick investigation, http://172.18.0.6:8080/ is the host & port that remix is listening to _inside the docker container_, while you should be opening localhost:3000 (the container maps the port 3000 to the port 8080 inside the container). I'm still surprised that you managed to see the login page by visiting http://172.18.0.6:8080/ though.
Please let me know if that solves the issue.

**Comment by marishlucas** [comment]
Hello,
Navigating to ``localhost:3000`` instead of the ``local-ip:8080`` (as it is shown in the logs) does indeed work. 
Quite confusing that it not shown anywhere in the logs (or docs).
Thanks for the response :-)

**Comment by Pascal-Delange** [comment]
Sorry for the confusion ! And thank you for taking the time to let us know, we'll make sur to update the doc accordingly (I'm not totally sure we can modify this log, though I'll double check)
