### ISSUE TITLE
[Feature] Delete data model

### ISSUE THREAD

**Issue by rajatm99** [checkmarble/marble#22]
we are only allowed to create new data table, not delete any.

**Comment by Pascal-Delange** [comment]
Hi Rajat,
Thanks for the feedback.
The main reason we haven't given the possibility so far is that deleting tables creates all sorts of difficult questions about not breaking existing scenarios.
Can you tell us some more about the usecase you have in mind? Is it mostly about convenience while first exploring the product, or do you see a need once in production ?

**Comment by rajatm99** [comment]
I've been exploring the product and created many test data models, fields, links, and scenarios. Now they are cluttering the interface with no practical use.

For example, I made a typo in one field and assigned the wrong data type to another while creating a model with 15 fields. These mistakes are now permanent since there's no option to delete them.

It would be helpful to have the ability to delete these entries to keep the UI clean and organised. This feature would also make it easier to correct errors and manage test data effectively.

Thanks for considering!

**Comment by Pascal-Delange** [comment]
Hi Rajat,

I understand the need ! 

However that's a really tricky feature request to make work in production. We understand that it's a pain point as users try the tool with test data model and scenarios, but we believe it should be much less of an issue once in production. So for now at least, we prefer to suggest you create a distinct organization for test and production, as we are a limited size team and prefer to focus on where we create most value for the decision engine's usability and stability.

I still hope we can come back to focus on this later !
