### ISSUE TITLE
Marble API : Error while Initializing Firebase

### ISSUE THREAD

**Issue by nickykln** [checkmarble/marble#32]
While removing the lines for Firebase Simulator 
FIREBASE_AUTH_EMULATOR_HOST_CLIENT=localhost:9099
FIREBASE_AUTH_EMULATOR_HOST_SERVER=localhost:9099

I have the following error :

marble-api       | panic: error getting Auth client: google: could not find default credentials. See https://cloud.google.com/docs/authentication/external/set-up-adc for more information

marble-api       | goroutine 1 [running]:
marble-api       | github.com/checkmarble/marble-backend/infra.InitializeFirebase({0x1bec0f8, 0xc00040aed0})
marble-api       | 	/go/src/app/infra/firebase_client.go:19 +0x73
marble-api       | github.com/checkmarble/marble-backend/cmd.RunServer()
marble-api       | 	/go/src/app/cmd/server.go:96 +0xb1d
marble-api       | main.main()
marble-api       | 	/go/src/app/main.go:35 +0x4eb

**Comment by Pascal-Delange** [comment]
Hi @nickykln ,
Thanks for pointing this out.
Can you please confirm that you have this issue when running the application in a non-GCP environment ? (I expect service account discovery to happen automatically in a GCP VM).
In any case, your workaround is the correct solution to this issue. I make a note to document this in the github repo in the next release.
You will also need to set proper values for all the `FIREBASE_` environment variables by the front-end container.

**Comment by Pascal-Delange** [comment]
Hi,
I added some help related to this in the latest release https://github.com/checkmarble/marble/pull/33
Thanks again for pointing out the issue
