### ISSUE TITLE
Data ingestion through API - Error 401

### ISSUE THREAD

**Issue by ondratkadlec** [checkmarble/marble#35]
I'm running the Marble with default setup of ports. So I just ran 'docker compose --env-file .env.example up' just like in the docs example. I'm able to ingest the data with via UI successfully, but when I try to ingest more data via API and run
`
import requests

url = "http://localhost:8080/ingestion/customers"
headers = {"content-type": "application/json"}
payload = {'object_id': 'cust6', 'updated_at': '2024-08-21T16:11:11Z', 'first_name': 'Arnold', 'last_name': 'White', 'static_segment': 'VIP'}
print(requests.post(url, json=payload, headers=headers))
`
I get error 401 - Unauthorized. Is there something I am missing? some API key that I should submit as well?
Thanks

**Comment by ondratkadlec** [comment]
I just discovered API tab in settings in the UI. I created an API key that I send in the headers of the POST request and it works!

**Comment by balzdur** [comment]
Glad you find out yourself 🎉 

By curiosity, how did you solve your issue ? We have a documented section about this [here](https://docs.checkmarble.com/docs/ingesting-data#by-api) in our doc but it may be difficult ot find by yourself. 
In order to improve discoverability of our product, it would be awesome to have your feedback.

**Comment by ondratkadlec** [comment]
in the UI, I went to Settings->API->New API Key. I didn't find this in the documentation, tho. I also didn't find, whether it's possible to ingest objects in batches e.g. multiple transactions at a time. Or does one need to iterate over the transactions and have one HTTP request per transaction?
Thanks

**Comment by Pascal-Delange** [comment]
Hi @ondratkadlec, 
Right now you can only ingest one object at a time, but we have batch ingestion by API on the To Do list (please do let us know about your constraints and planned usage, any feedback is useful for us to prioritize features as best as possible).

**Comment by ondratkadlec** [comment]
hello @Pascal-Delange, my planned usage so far is explore the solution in order to compare it with the paid alternatives. I'll be happy to give feedback later!
