### ISSUE TITLE
[BUG] Foreign Key Missing on decision_rules (decision_id > decision)

### ISSUE THREAD

**Issue by nickykln** [checkmarble/marble#60]
**Describe the bug**
Foreign Key Missing on decision_rules (decision_id > decision) + cascade delete.

**To Reproduce**
1. Delete a decision in cascade mode (or truncate)
2. The associated decision_rules stay there

**Expected behavior**
Having a foreign key with on delete behaviour.
Can be useful for maintenance tasks. 

Thanks

**Comment by Pascal-Delange** [comment]
Hi @nickykln ,
In fact it's not exactly a bug, in any case is voluntary. The reason behind it is the following:
- the decision_rules table is a write-heavy, read-light table
- for cascade delete to work well on a large table, a secondary index is necessary on the referenced field in the child table
- in practice, this means for every insert, the DB needs to make 2 additional actions: check that the referenced field is still present in the parent table, write a secondary index
- we found that a very sizable amount of cpu-time on our DB was spent just keeping this FK bookkeeping on this one table up to date

Generally speaking, the benefits of FKs break down for tables that are large, especially if they are heavily written.

This decision indeed comes at the cost of requiring manual cleanup for any "orphan" decision rules.
